### PR TITLE
Landing Page Minor Changes

### PR DESCRIPTION
**Pull request by dpaulos6**
# Description

The landing page was slightly adjusted.
Also changed the testimonial's cards `@` sign to a lucide-react icon.

## Type of change

Please delete options that are not relevant.

- [x] Minor style adjustments (Non-breaking adjustments for a better UI)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] The code works fine on my machine.
- [ ] I have modified the build steps if changed.

### CODE REVIEW

**Comment by mezotv** [comment]
@NizarAbiZaher any updates on this?

**Comment by nizzyabi** [comment]
> @NizarAbiZaher any updates on this?

yes reading code rn. been travelling

**Comment by nizzyabi** [comment]
Hey paulos, trying to push but there seems to be some conflicts, could you update?

**Comment by dpaulos6** [comment]
> Hey paulos, trying to push but there seems to be some conflicts, could you update?

Fixed the conflicts, should be good to go now!

**Pull request merged**
